services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker/database:/docker-entrypoint-initdb.d

  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_DATABASE}

volumes:
  database_data:
